### ISSUE TITLE
在连接多个bot的时候自动修改群名片会失效

### ISSUE THREAD

**Issue by yuan488** [forchannot/nonebot_plugin_rename#3]
在多个bot连接时仅有一个bot能成功自动修改群名片，其他的bot会报WARNING：
`03-16 00:38:19 [WARNING] nonebot_plugin_rename | 更改群名片失败，可能是机器人不存在或被风控`

**Comment by forchannot** [comment]
更新了，请尝试使用新版，之前没接触过多bot的处理，无法测试，可以麻烦你测试下

**Comment by yuan488** [comment]
目前看来全部bot都无法更改群名片，我尝试把yaml文件删除后重新`设置群名片 12` bot回复设置成功但yaml文件里并没有东西

**Comment by forchannot** [comment]
> 目前看来全部bot都无法更改群名片，我尝试把yaml文件删除后重新`设置群名片 12` bot回复设置成功但yaml文件里并没有东西

emmm，把yaml删除后重启下机器人再发送命令呢？后台有没有报错啥的，我这边是没问题的

**Comment by forchannot** [comment]
稍等，我改一下

**Comment by forchannot** [comment]
> 目前看来全部bot都无法更改群名片，我尝试把yaml文件删除后重新`设置群名片 12` bot回复设置成功但yaml文件里并没有东西

再试一次呢，之前改漏了

**Comment by yuan488** [comment]
问题已修复，感谢大佬

**Comment by forchannot** [comment]
好的，issue关了，还有问题可以随时reopen
